name: CMake

on: [push, pull_request]

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Stats
      run: ./run.sh stats

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [Debug, RelWithDebInfo, Release]

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

    - name: Cache externals
      uses: actions/cache@v2
      with:
        path: ${{github.workspace}}/build/ext
        key: ${{runner.os}}-ext-${{hashFiles('**/ext/*.cmake')}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

    - name: Test
      if: ${{ matrix.build_type != 'Release' && matrix.build_type != 'MinSizeRel' }}
      working-directory: ${{github.workspace}}/build
      run: ctest -V -C ${{matrix.build_type}}
      env:
        CTEST_OUTPUT_ON_FAILURE: 1
